### ISSUE TITLE
The given version [19] is not supported, only version 1 to 10 is supported in this build. 

### ISSUE THREAD

**Issue by hallejuyahaha** [mediar-ai/screenpipe#1034]
**describe the bug**
brief description of the bug.

**system info**
- os: [ windows 11]
- screenpipe version: [e.g. 0.2.19]

![image](https://github.com/user-attachments/assets/c5b21b80-7f0f-434b-b504-5cf045ecc3d3)

The given version [19] is not supported, only version 1 to 10 is supported in this build.
thread 'tokio-runtime-worker' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ort-2.0.0-rc.6\src/lib.rs:223:57:
Failed to initialize ORT API

**Comment by louis030195** [comment]
how did you install?

**Comment by louis030195** [comment]
@Neptune650

**Comment by Neptune650** [comment]
> @Neptune650

Likely a build issue in the user side

**Comment by Neptune650** [comment]
> > how did you install?
> 
> i use install.ps1 and use screenpipe-0.2.20-x86_64-pc-windows-msvc.zip all throw this error

What Windows 11 edition

**Comment by iWangJiaxiang** [comment]
Hi, I just ran into this issue, too. 

I installed screenpipe using the `install.ps1` script.

Here is my environment.

System: Win11 23H2 (Build 226314602)

**Comment by argenisleon** [comment]
Same problem here. For installing using:
`irm https://raw.githubusercontent.com/mediar-ai/screenpipe/main/install.ps1 | iex`
from `PowerShell`
```
OS Name	Microsoft Windows 11 Home
Version	10.0.22635 Build 22635
```

**Comment by louis030195** [comment]
until we find a fix, maybe using `--disable-audio` will prevent the crash (since we only use ONNX in audio)

**Comment by divanshu-go** [comment]
@louis030195 
https://github.com/mediar-ai/screenpipe/issues/943
I guess It was fixed.

**Comment by divanshu-go** [comment]
https://github.com/mediar-ai/screenpipe/issues/794#issuecomment-2528477757
see this comment

**Comment by divanshu-go** [comment]
More references , 
https://github.com/microsoft/onnxruntime/issues/11230

**Comment by louis030195** [comment]
/bounty 200

@Neptune650 coming back to this 

some users still have this

**Comment by Neptune650** [comment]
> @Neptune650 did 2 PRs
>  #830
> 
> #991  
> maybe we are lacking something .

The root cause is that the user doesn't have Win11 or the necessary vcredist libraries installed
Obviously the most simple way to go about this would be to tell the user to install these, but might not be too factible

The error has come from different parts, so each PR added it to one. A more permanent solution would be to install vcredist in the end user side somehow.

**Comment by Neptune650** [comment]
> > @Neptune650 did 2 PRs
> >  #830
> > 
> > #991  
> > maybe we are lacking something .
> 
> The root cause is that the user doesn't have Win11 or the necessary vcredist libraries installed
> Obviously the most simple way to go about this would be to tell the user to install these, but might not be too factible
> 
> The error has come from different parts, so each PR added it to one. A more permanent solution would be to install vcredist in the end user side somehow.

@louis030195 I'm sending a PR to install vcredist in the install script

Since that's what's causing this issue to begin with.

**Comment by louis030195** [comment]
issue still not solved btw
