### ISSUE TITLE
Repeated "Access Denied (0x80070005)" Errors Potentially Related to Audio Handling

### ISSUE THREAD

**Issue by meltiso** [mediar-ai/screenpipe#370]
**Description**:  
During the execution of the screenpipe application on Windows 11, multiple instances of the following error were observed in the logs:

```
2024-09-27T11:48:59.843585Z ERROR xcap::platform::impl_window: Access denied. (0x80070005) 
2024-09-27T11:48:59.844279Z ERROR xcap::platform::impl_window: Access denied. (0x80070005) 
2024-09-27T11:49:00.544055Z ERROR xcap::platform::impl_window: Access denied. (0x80070005) 
2024-09-27T11:49:00.547017Z ERROR xcap::platform::impl_window: Access denied. (0x80070005)
```

This error seems to occur frequently and may be related to attempts to access audio devices, such as microphones or speakers, as indicated by the logs surrounding the error:

```
2024-09-27T11:48:59.627813Z INFO screenpipe_server::core: device Réseau de microphones (Technologie Intel® Smart Sound pour microphones numériques) (input) inserting audio chunk: "" 
2024-09-27T11:49:01.618070Z INFO screenpipe_server::core: Finished record_and_transcribe for device Haut-parleurs (Realtek(R) Audio) (output) (iteration 7)
```

**Steps to Reproduce:**
1. Run the screenpipe application on a Windows system with active audio devices (input/output).
2. Observe the logs to see if the "Access Denied (0x80070005)" errors appear during audio capture or playback.

**Expected Behavior:**
The application should have the necessary permissions to access audio devices, or it should handle the permission error gracefully with proper diagnostics.

**Additional Information:**
- OS: Windows 11
- Error Code: 0x80070005 (Access Denied)
- Logs suggest that the issue might be related to microphone or speaker access.

**Comment by louis030195** [comment]
@meltiso thanks this is related to #320 which is related to screen capture, not mic, did you run the CLI or app? did you build from source?

also curious do you have any window/app opened with admin right?

if you run the app/cli in admin this should solve the issue, but someone mentioned this issue could be related that the user have some apps opened in admin right and the screen capture is unable to capture these windows without elevated right itself, would appreciate if you can say if this is your case 🙏

**Comment by meltiso** [comment]
Hey @louis030195 Thanks for all your answers 😊 I purchased the Windows app and haven't tried the CLI yet 

I closed all my apps and ran Screenpipe with admin rights, but I'm still getting errors. 

But I've just noticed the data folder is being populated with MP4 files every minute for both of my screens, whether I'm in admin mode or not. So despite the errors, it works! As you explain in #369 the errors should be due to attempts to access two screen IDs that don't appear in the list of monitors in the settings.
